#!/bin/sh

TITLE="Loading"
COMMAND=""
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# shellcheck disable=SC2317
cleanup() (
    killall minui-presenter >/dev/null 2>&1 || true
)

main() {
    trap "cleanup" EXIT INT TERM HUP QUIT

    if [ ! -f "$SCRIPT_DIR/minui-presenter" ]; then
        echo "$SCRIPT_DIR/minui-presenter not found."
        exit 1
    fi

    chmod +x "$SCRIPT_DIR/minui-presenter"

    while [ $# -gt 0 ]; do
        case "$1" in
            --title)
                TITLE="$2"
                shift 2
                ;;
            --*)
                shift
                if [ $# -gt 0 ] && [ "${1#--}" = "$1" ]; then
                    shift
                fi
                ;;
            *)
                COMMAND="$*"
                break
                ;;
        esac
    done

    if [ -z "$COMMAND" ]; then
        echo "Usage: $0 [--title title] command [args...]"
        exit 1
    fi

    sh -c "$COMMAND" &
    CMD_PID=$!

    killall minui-presenter >/dev/null 2>&1 || true
    "$SCRIPT_DIR/minui-presenter" --disable-auto-sleep \
        --message "$TITLE, please wait..." --timeout -1 &

    wait $CMD_PID
    exit_code=$?

    exit $exit_code
}

main "$@"
